name: Station Container Basic Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Test Station Container Basic Functionality
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          station-cicd-security-demo:latest \
          bash -c "
            echo '=== Testing Station CLI ===' && \
            stn --version && \
            echo '=== Testing Ship CLI ===' && \
            ship --help | head -5 && \
            echo '=== Testing Docker CLI ===' && \
            docker --version && \
            echo '=== Testing Dagger functionality ===' && \
            cd /workspace && \
            ls -la
          "
      continue-on-error: false
    
    - name: Test Ship Tools Discovery
      run: |
        docker run --rm \
          station-cicd-security-demo:latest \
          bash -c "
            echo '=== Testing Ship MCP Discovery ===' && \
            ship list-mcps | head -20
          "
      continue-on-error: true

    - name: Generate Test Report
      run: |
        echo "# Station Container Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Container: station-cicd-security-demo:latest" >> $GITHUB_STEP_SUMMARY
        echo "## Test Date: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Station CLI functional test complete" >> $GITHUB_STEP_SUMMARY
        echo "✅ Ship CLI integration test complete" >> $GITHUB_STEP_SUMMARY
        echo "✅ Docker CLI availability verified" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "_Container successfully tested with GitHub Actions via act_" >> $GITHUB_STEP_SUMMARY